---
- name: Generate and Start Docker Compose
  hosts: test
  gather_facts: false

  vars:
    odoo_port: '14'
    odoo_version: '14.0'
    postgres_version: '15'

  tasks:
    - name: Ensure directory for the Odoo version exists
      file:
        path: /home/zivi/Services/odoo-docker-test/{{ odoo_version }}
        state: directory

    - name: Render Docker Compose template
      template:
        src: ../../templates/docker-compose.j2
        dest: /home/zivi/Services/odoo-docker-test/{{ odoo_version }}/docker-compose.yml

    - name: Stop Docker Compose
      command: docker compose down
      args:
        chdir: /home/zivi/Services/odoo-docker-test/{{ odoo_version }}

    - name: Docker Compose pull
      command: docker compose pull
      args:
        chdir: /home/zivi/Services/odoo-docker-test/{{ odoo_version }}

    - name: Start Docker Compose
      command: docker compose up -d
      args:
        chdir: /home/zivi/Services/odoo-docker-test/{{ odoo_version }}
